name: Python its-client

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Set up python 3.11
        uses: actions/setup-python@v5.3.0
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          cd python/its-client
          python -m pip install --upgrade pip
          pip install coverage black wheel
          if  [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run black
        run: |
          cd python/its-client
          black --diff --check .
      - name: Run Unit Tests and generate coverage report
        run: |
          cd python/its-client
          python -m unittest -v
          coverage run -m unittest
          coverage report
          coverage html
      - name: Run package creation
        run: |
          cd python/its-client
          python setup.py bdist_wheel
