name: Python packages

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - iot3
          - its-info
          - its-interqueuemanager
          - its-quadkeys
          - its-status
          - its-vehicle
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Set up python 3.11
        uses: actions/setup-python@v5.3.0
        with:
          python-version: "3.11"
      - name: Install tooling dependencies
        run: |
          pip --disable-pip-version-check --no-cache-dir install \
              -r python/requirements-tests.txt
      - name: Run black
        run: |
          black --diff --check python/${{ matrix.package }}
      - name: Run package creation
        run: |
          python -m build python/${{ matrix.package }}
      - name: Sanity checks of generated package
        run: |
          twine check --strict python/${{ matrix.package }}/dist/*
