name: Python its-quadkeys

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Set up python 3.11
        uses: actions/setup-python@v5.3.0
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          cd python/its-quadkeys
          python -m pip install --upgrade pip
          pip install black wheel
          pip install -r requirements.txt
      - name: Run black
        run: |
          cd python/its-quadkeys
          black --diff --check .
      - name: Run test-suite
        run: |
          cd python/its-quadkeys
          ./quadkeys-test
      - name: Run package creation
        run: |
          cd python/its-quadkeys
          python setup.py bdist_wheel
