name: Rust

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - name: Run rustfmt
        run: |
          cd rust
          cargo fmt -- --check
      - name: Run Clippy
        run: |
          cd rust
          cargo clippy -- -D clippy::all

  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd rust
          cargo build --verbose
      - name: Build Release
        run: |
          cd rust
          cargo build --release --verbose
      - name: Build  mobility feature
        run: |
          cd rust
          cargo build --features mobility --verbose
      - name: Build telemetry feature
        run: |
          cd rust
          cargo build --features telemetry --verbose
      - name: Build geo_routing feature
        run: |
          cd rust
          cargo build --features geo_routing --verbose
      - name: Build all features
        run: |
          cd rust
          cargo build --all-features --verbose
      - name: Build all features Release
        run: |
          cd rust
          cargo build --all-features --release --verbose
      - name: Build json_counter example
        run: |
          cd rust
          cargo build --example json_counter --verbose
      - name: Build telemetry example
        run: |
          cd rust
          cargo build --example telemetry --features telemetry --verbose
      - name: Build copycat example
        run: |
          cd rust
          cargo build --example copycat --features geo_routing --verbose
      - name: Build copycat example with telemetry
        run: |
          cd rust
          cargo build --example copycat --features geo_routing,telemetry --verbose
      - name: Build collector example
        run: |
          cd rust
          cargo build --example collector --verbose
      - name: Build collector example with telemetry
        run: |
          cd rust
          cargo build --example collector --features telemetry --verbose
      - name: Build all examples
        run: |
          cd rust
          cargo build --examples --features telemetry,geo_routing --verbose
      - name: Build all examples Release
        run: |
          cd rust
          cargo build --examples --features "telemetry,geo_routing" --release --verbose

  test:
    name: Tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          cd rust
          cargo test --verbose
      - name: Test mobility feature
        run: |
          cd rust
          cargo test --features mobility --verbose
      - name: Test telemetry feature
        run: |
          cd rust
          cargo test --features telemetry --verbose
      - name: Test geo_routing feature
        run: |
          cd rust
          cargo test --features geo_routing --verbose
      - name: Test all features
        run: |
          cd rust
          cargo test --all-features --verbose
      - name: Test all examples
        run: |
          cd rust
          cargo test --examples --verbose
