name: Rust Crates

on:
  push:
    tags:
      - rust.*

env:
  CARGO_TERM_COLOR: always

jobs:
  publish_lib:
    name: Publish the library
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - name: Publish the ITS library
        run: |
          cd rust/
          cargo publish --token ${{ secrets.CRATES_IO }}
