name: Swift ITSClient

on:
  push:
    branches:
      - main
      - develop
      - 'swift-*'

  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode 16
        run: |
          sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer

      - name: Build
        run: |
          cd swift/ITSClient
          swift build

  test:
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode 16
        run: |
          sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer

      - name: Build
        run: |
          cd swift/ITSClient
          xcodebuild -scheme ITSClient test -testPlan ITSClient-UnitTests -destination "name=iPhone 16"
